import { useState, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { exportCSV, exportMarkdown, exportTSV, saveExport } from '@/services/export';
import { computeTotal } from '@/services/balance';
import { computeDailyBalances, groupByMonth, toISODate } from '@/lib/chart-utils';
import { FileText, FileSpreadsheet, FileDown, ClipboardCopy } from 'lucide-react';
import type { TransactionRow } from '../../../shared/ipc-types';
import { useUiStore } from '@/stores/ui-store';

// --- Shared input styles ---

const INPUT_CLASS =
  'w-full h-9 px-3 text-sm bg-background border border-border-subtle rounded-md focus:outline-none focus:ring-2 focus:ring-fidra-teal/40 focus:border-fidra-teal transition-fidra placeholder:text-muted-foreground/50';

// --- Main ---

interface ExportTabProps {
  filteredTransactions: TransactionRow[];
  allTransactions: TransactionRow[];
  startDate: string;
  endDate: string;
  sheetName?: string;
  plannedData?: { description: string; date: string; amount: string; type: string }[];
}

export function ExportTab({
  filteredTransactions,
  allTransactions,
  startDate,
  endDate,
  sheetName,
  plannedData,
}: ExportTabProps) {
  return (
    <div className="space-y-8">
      <QuickExportSection
        filteredTransactions={filteredTransactions}
        allTransactions={allTransactions}
        startDate={startDate}
        endDate={endDate}
        sheetName={sheetName}
        plannedData={plannedData}
      />
      <div className="border-t border-border-subtle" />
      <ReportBuilderSection
        allTransactions={allTransactions}
        sheetName={sheetName}
        plannedData={plannedData}
      />
    </div>
  );
}

// --- Quick Export ---

function QuickExportSection({
  filteredTransactions,
  allTransactions,
  startDate,
  endDate,
  sheetName,
  plannedData,
}: ExportTabProps) {
  const count = filteredTransactions.length;
  const isEmpty = count === 0;

  const handleExportCSV = useCallback(async () => {
    if (isEmpty) return;
    const content = exportCSV(filteredTransactions, true);
    await saveExport(content, 'report.csv', [{ name: 'CSV', extensions: ['csv'] }]);
  }, [filteredTransactions, isEmpty]);

  const handleExportMarkdown = useCallback(async () => {
    if (isEmpty) return;
    const content = exportMarkdown(filteredTransactions, true);
    await saveExport(content, 'report.md', [{ name: 'Markdown', extensions: ['md'] }]);
  }, [filteredTransactions, isEmpty]);

  const handleExportPDF = useCallback(async () => {
    if (isEmpty) return;
    const openingBalance = computeTotal(allTransactions.filter((t) => t.date < startDate));
    const now = new Date();
    const { renderReportHTML } = await import('@/services/report-html');
    const balData = computeDailyBalances(allTransactions, startDate, endDate).map((p) => ({
      date: p.dateISO,
      balance: p.balance,
    }));
    const monthData = groupByMonth(filteredTransactions).map((m) => ({
      month: m.month,
      income: m.income,
      expense: m.expense,
    }));
    const generatedStr = `${now.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}, ${now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}`;
    const html = renderReportHTML({
      startDate,
      endDate,
      generatedDate: generatedStr,
      sheetName,
      openingBalance,
      includeActivities: true,
      balanceData: balData,
      monthlyData: monthData,
      plannedData,
      transactions: filteredTransactions,
    });
    const pdfBytes = await window.api.printToPDF(html, {
      footerText: `Generated by Fidra \u00b7 ${generatedStr}`,
    });
    const result = await window.api.showSaveDialog({
      title: 'Export PDF',
      defaultPath: 'report.pdf',
      filters: [{ name: 'PDF', extensions: ['pdf'] }],
    });
    if (!result.canceled && result.filePath) {
      await window.api.writeFileBinary(result.filePath, pdfBytes);
    }
  }, [filteredTransactions, allTransactions, startDate, endDate, sheetName, plannedData, isEmpty]);

  const handleCopyClipboard = useCallback(async () => {
    if (isEmpty) return;
    const tsv = exportTSV(filteredTransactions, true);
    await navigator.clipboard.writeText(tsv);
  }, [filteredTransactions, isEmpty]);

  return (
    <section>
      <div className="mb-4">
        <h3 className="text-sm font-display font-semibold">Quick Export</h3>
        <p className="text-xs text-muted-foreground mt-0.5">
          Export {count} filtered transaction{count !== 1 ? 's' : ''} in one click
        </p>
      </div>

      <div className="grid grid-cols-4 gap-3 max-w-2xl">
        <button
          type="button"
          disabled={isEmpty}
          onClick={handleExportCSV}
          className="group flex flex-col items-center gap-2 rounded-lg border border-border-subtle bg-surface-raised/50 p-4 hover:border-fidra-teal/50 hover:bg-fidra-teal/5 transition-fidra disabled:opacity-40 disabled:cursor-not-allowed"
        >
          <FileSpreadsheet className="h-6 w-6 text-muted-foreground group-hover:text-fidra-teal transition-colors" />
          <span className="text-sm font-medium">CSV</span>
        </button>

        <button
          type="button"
          disabled={isEmpty}
          onClick={handleExportMarkdown}
          className="group flex flex-col items-center gap-2 rounded-lg border border-border-subtle bg-surface-raised/50 p-4 hover:border-fidra-teal/50 hover:bg-fidra-teal/5 transition-fidra disabled:opacity-40 disabled:cursor-not-allowed"
        >
          <FileText className="h-6 w-6 text-muted-foreground group-hover:text-fidra-teal transition-colors" />
          <span className="text-sm font-medium">Markdown</span>
        </button>

        <button
          type="button"
          disabled={isEmpty}
          onClick={handleExportPDF}
          className="group flex flex-col items-center gap-2 rounded-lg border border-border-subtle bg-surface-raised/50 p-4 hover:border-fidra-teal/50 hover:bg-fidra-teal/5 transition-fidra disabled:opacity-40 disabled:cursor-not-allowed"
        >
          <FileDown className="h-6 w-6 text-muted-foreground group-hover:text-fidra-teal transition-colors" />
          <span className="text-sm font-medium">PDF</span>
        </button>

        <button
          type="button"
          disabled={isEmpty}
          onClick={handleCopyClipboard}
          className="group flex flex-col items-center gap-2 rounded-lg border border-border-subtle bg-surface-raised/50 p-4 hover:border-fidra-teal/50 hover:bg-fidra-teal/5 transition-fidra disabled:opacity-40 disabled:cursor-not-allowed"
        >
          <ClipboardCopy className="h-6 w-6 text-muted-foreground group-hover:text-fidra-teal transition-colors" />
          <span className="text-sm font-medium">Clipboard</span>
        </button>
      </div>
    </section>
  );
}

// --- Report Builder ---

function ReportBuilderSection({
  allTransactions,
  sheetName,
  plannedData,
}: {
  allTransactions: TransactionRow[];
  sheetName?: string;
  plannedData?: { description: string; date: string; amount: string; type: string }[];
}) {
  const reportOrgName = useUiStore((s) => s.reportOrgName);
  const setReportOrgName = useUiStore((s) => s.setReportOrgName);
  const [title, setTitle] = useState(reportOrgName);
  const [reportStartDate, setReportStartDate] = useState(() => {
    const d = new Date();
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-01`;
  });
  const [reportEndDate, setReportEndDate] = useState(() => toISODate(new Date()));
  const [includeSummary, setIncludeSummary] = useState(true);
  const [includeCategories, setIncludeCategories] = useState(true);
  const [includeActivities, setIncludeActivities] = useState(true);
  const [includeTransactions, setIncludeTransactions] = useState(true);
  const [format, setFormat] = useState<'markdown' | 'pdf'>('pdf');
  const [countThreshold, setCountThreshold] = useState(5);
  const [amountThreshold, setAmountThreshold] = useState(0);
  const [filterMode, setFilterMode] = useState<'or' | 'and'>('or');

  // Persist org name to global settings when it changes
  const handleTitleChange = useCallback((value: string) => {
    setTitle(value);
    setReportOrgName(value);
  }, [setReportOrgName]);

  const handleGenerate = useCallback(async () => {
    const filtered = allTransactions.filter(
      (t) => t.status !== 'planned' && t.date >= reportStartDate && t.date <= reportEndDate,
    );
    if (filtered.length === 0) return;

    if (format === 'markdown') {
      const { generateReportMarkdown } = await import('@/services/report-builder');
      const content = generateReportMarkdown(filtered, {
        title: title || 'Financial Report',
        startDate: reportStartDate,
        endDate: reportEndDate,
        includeSummary,
        includeMonthlyBreakdown: includeCategories,
        includeCategoryBreakdown: includeCategories,
        includeTransactionTable: includeTransactions,
      });
      await saveExport(content, 'report.md', [{ name: 'Markdown', extensions: ['md'] }]);
    } else {
      const ob = computeTotal(allTransactions.filter((t) => t.date < reportStartDate));
      const now = new Date();
      const balData = computeDailyBalances(allTransactions, reportStartDate, reportEndDate).map(
        (p) => ({ date: p.dateISO, balance: p.balance }),
      );
      const monthData = groupByMonth(filtered).map((m) => ({
        month: m.month,
        income: m.income,
        expense: m.expense,
      }));
      const { renderReportHTML } = await import('@/services/report-html');
      const generatedStr = `${now.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}, ${now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}`;
      const html = renderReportHTML({
        title: title || undefined,
        startDate: reportStartDate,
        endDate: reportEndDate,
        generatedDate: generatedStr,
        sheetName,
        openingBalance: ob,
        includeSummary,
        includeCategories,
        includeActivities,
        includeTransactions,
        subItemFilter: { countThreshold, amountThreshold, mode: filterMode },
        balanceData: balData,
        monthlyData: monthData,
        plannedData,
        transactions: filtered,
      });
      const pdfBytes = await window.api.printToPDF(html, {
        footerText: `Generated by Fidra \u00b7 ${generatedStr}`,
      });
      const result = await window.api.showSaveDialog({
        title: 'Save Report',
        defaultPath: 'report.pdf',
        filters: [{ name: 'PDF', extensions: ['pdf'] }],
      });
      if (!result.canceled && result.filePath) {
        await window.api.writeFileBinary(result.filePath, pdfBytes);
      }
    }
  }, [
    allTransactions, reportStartDate, reportEndDate, title, format, sheetName,
    includeSummary, includeCategories, includeActivities, includeTransactions,
    countThreshold, amountThreshold, filterMode, plannedData,
  ]);

  return (
    <section className="max-w-3xl">
      <div className="mb-5">
        <h3 className="text-sm font-display font-semibold">Custom Report Builder</h3>
        <p className="text-xs text-muted-foreground mt-0.5">
          Generate a formatted financial report as PDF or Markdown with full control over sections
        </p>
      </div>

      <div className="space-y-6">
        {/* Row 1: Org name + date range */}
        <div className="grid grid-cols-[1fr_auto_auto] gap-4 items-end">
          <div>
            <div className="flex items-center gap-1.5 mb-1.5">
              <div className="w-1.5 h-1.5 rounded-full bg-fidra-teal" title="Persisted across sessions" />
              <Label className="text-xs text-muted-foreground">Organisation Name</Label>
            </div>
            <input
              className={INPUT_CLASS}
              placeholder="e.g. University of St Andrews Sub-Aqua Club"
              value={title}
              onChange={(e) => handleTitleChange(e.target.value)}
            />
          </div>
          <div>
            <Label className="text-xs text-muted-foreground mb-1.5 block">From</Label>
            <input
              type="date"
              className={INPUT_CLASS}
              value={reportStartDate}
              onChange={(e) => setReportStartDate(e.target.value)}
            />
          </div>
          <div>
            <Label className="text-xs text-muted-foreground mb-1.5 block">To</Label>
            <input
              type="date"
              className={INPUT_CLASS}
              value={reportEndDate}
              onChange={(e) => setReportEndDate(e.target.value)}
            />
          </div>
        </div>

        {/* Row 2: Sections + Category detail side-by-side */}
        <div className="grid grid-cols-2 gap-6">
          {/* Sections */}
          <div className="rounded-lg border border-border-subtle bg-surface-raised/50 p-4 space-y-3">
            <Label className="text-xs font-display font-semibold uppercase tracking-wider text-muted-foreground">
              Sections to Include
            </Label>
            <div className="space-y-2.5">
              <label className="flex items-center gap-2.5 cursor-pointer">
                <Checkbox
                  id="rb-summary"
                  checked={includeSummary}
                  onCheckedChange={(v) => setIncludeSummary(!!v)}
                />
                <span className="text-sm">Summary</span>
              </label>
              <label className="flex items-center gap-2.5 cursor-pointer">
                <Checkbox
                  id="rb-categories"
                  checked={includeCategories}
                  onCheckedChange={(v) => setIncludeCategories(!!v)}
                />
                <span className="text-sm">Income & Expenditure Breakdown</span>
              </label>
              <label className="flex items-center gap-2.5 cursor-pointer">
                <Checkbox
                  id="rb-activities"
                  checked={includeActivities}
                  onCheckedChange={(v) => setIncludeActivities(!!v)}
                />
                <span className="text-sm">Income & Expenditure by Activity</span>
              </label>
              <label className="flex items-center gap-2.5 cursor-pointer">
                <Checkbox
                  id="rb-txntable"
                  checked={includeTransactions}
                  onCheckedChange={(v) => setIncludeTransactions(!!v)}
                />
                <span className="text-sm">Transaction Register</span>
              </label>
            </div>
          </div>

          {/* Category detail thresholds */}
          <div className={`rounded-lg border border-border-subtle bg-surface-raised/50 p-4 space-y-3 transition-opacity ${includeCategories ? '' : 'opacity-40 pointer-events-none'}`}>
            <Label className="text-xs font-display font-semibold uppercase tracking-wider text-muted-foreground">
              Category Detail Thresholds
            </Label>
            <p className="text-[11px] text-muted-foreground leading-snug">
              Show description sub-items within each category when they meet these thresholds.
            </p>
            <div className="grid grid-cols-[1fr_auto_1fr] items-end gap-2">
              <div>
                <label className="text-[11px] text-muted-foreground">Transactions</label>
                <input
                  type="number"
                  min={1}
                  className={`${INPUT_CLASS} mt-1 tabular-nums`}
                  value={countThreshold}
                  onChange={(e) => setCountThreshold(Math.max(1, parseInt(e.target.value) || 1))}
                />
              </div>
              <button
                type="button"
                className="h-9 px-3 text-xs font-display font-semibold rounded-md border border-border-subtle hover:bg-muted/50 transition-fidra"
                onClick={() => setFilterMode((m) => (m === 'or' ? 'and' : 'or'))}
              >
                {filterMode.toUpperCase()}
              </button>
              <div>
                <label className="text-[11px] text-muted-foreground">{'Amount (\u00a3)'}</label>
                <input
                  type="number"
                  min={0}
                  step={50}
                  className={`${INPUT_CLASS} mt-1 tabular-nums`}
                  value={amountThreshold}
                  onChange={(e) =>
                    setAmountThreshold(Math.max(0, parseFloat(e.target.value) || 0))
                  }
                />
              </div>
            </div>
            <p className="text-[11px] text-muted-foreground">
              {filterMode === 'or'
                ? `Show if \u2265 ${countThreshold} transactions or total \u2265 \u00a3${amountThreshold.toLocaleString()}`
                : `Show if \u2265 ${countThreshold} transactions and total \u2265 \u00a3${amountThreshold.toLocaleString()}`}
              {amountThreshold <= 0 && filterMode === 'or'
                ? ' (amount filter disabled \u2014 set > 0 to enable)'
                : ''}
            </p>
          </div>
        </div>

        {/* Row 3: Format + Generate */}
        <div className="flex items-center justify-between pt-2 border-t border-border-subtle">
          <div className="flex items-center gap-3">
            <Label className="text-xs text-muted-foreground">Output format</Label>
            <Select value={format} onValueChange={(v) => setFormat(v as 'markdown' | 'pdf')}>
              <SelectTrigger className="w-36 h-9">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="pdf">PDF</SelectItem>
                <SelectItem value="markdown">Markdown</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <Button onClick={handleGenerate} size="lg" className="gap-2">
            <FileDown className="h-4 w-4" />
            Generate Report
          </Button>
        </div>
      </div>
    </section>
  );
}
