import type {
  AttachmentRow,
  CloudServerConfig,
  CloudStatus,
  InvoiceDefaults,
  InvoiceRow,
  LocalSyncConfig,
  LocalSyncStatus,
  PlannedTemplateRow,
  SheetRow,
  TransactionRow,
} from '../../shared/ipc-types';
import type { UiPreferences } from '../../shared/global-settings-types';

export interface DemoDataState {
  transactions: TransactionRow[];
  sheets: SheetRow[];
  plannedTemplates: PlannedTemplateRow[];
  attachments: AttachmentRow[];
  invoices: InvoiceRow[];
  incomeCategories: string[];
  expenseCategories: string[];
  activityNotes: Record<string, string>;
  currentSheet: string;
  uiPreferences: UiPreferences;
  fyStartMonth: number;
  profile: { name: string; initials: string };
  currentUser: { displayName: string; source: 'auth' | 'profile' | 'none' } | null;
  dbInfo: { path: string; name: string };
  invoiceDefaults: InvoiceDefaults;
  cloudConfig: CloudServerConfig | null;
  cloudStatus: CloudStatus;
  localSyncConfig: LocalSyncConfig | null;
  localSyncStatus: LocalSyncStatus;
}

const sheets: SheetRow[] = [
  {
    id: 'sheet-general',
    name: 'General',
    is_virtual: 0,
    is_planned: 0,
    sort_order: 1,
    created_at: '2026-01-01T09:00:00.000Z',
  },
  {
    id: 'sheet-training',
    name: 'Training',
    is_virtual: 0,
    is_planned: 0,
    sort_order: 2,
    created_at: '2026-01-01T09:05:00.000Z',
  },
  {
    id: 'sheet-expeditions',
    name: 'Expeditions',
    is_virtual: 0,
    is_planned: 0,
    sort_order: 3,
    created_at: '2026-01-01T09:10:00.000Z',
  },
  {
    id: 'sheet-social',
    name: 'Social',
    is_virtual: 0,
    is_planned: 0,
    sort_order: 4,
    created_at: '2026-01-01T09:15:00.000Z',
  },
];

const transactions: TransactionRow[] = [
  {
    id: 'tx-001',
    date: '2026-01-08',
    description: 'Membership dues batch',
    amount: '560.00',
    type: 'income',
    status: 'approved',
    sheet: 'General',
    category: 'Membership',
    party: 'Club members',
    reference: 'JAN-DUES',
    activity: '2026-01-08 Membership Dues Run',
    notes: 'January standing dues received.',
    version: 1,
    created_at: '2026-01-08T10:12:00.000Z',
    modified_at: '2026-01-08T10:12:00.000Z',
    modified_by: 'Demo Treasurer',
  },
  {
    id: 'tx-002',
    date: '2026-02-03',
    description: 'Pool lane booking',
    amount: '120.00',
    type: 'expense',
    status: 'approved',
    sheet: 'Training',
    category: 'Training',
    party: 'University Sports Centre',
    reference: 'POOL-0203',
    activity: '2026-02-03 Pool Training Night',
    notes: null,
    version: 1,
    created_at: '2026-02-03T12:45:00.000Z',
    modified_at: '2026-02-03T12:45:00.000Z',
    modified_by: 'Demo Treasurer',
  },
  {
    id: 'tx-003',
    date: '2026-02-18',
    description: 'Equipment servicing',
    amount: '78.50',
    type: 'expense',
    status: 'approved',
    sheet: 'General',
    category: 'Equipment',
    party: 'Aqua Workshop',
    reference: 'REG-SVC-18',
    activity: null,
    notes: 'Regulator service for club set.',
    version: 1,
    created_at: '2026-02-18T14:21:00.000Z',
    modified_at: '2026-02-18T14:21:00.000Z',
    modified_by: 'Demo Treasurer',
  },
  {
    id: 'tx-004',
    date: '2026-03-04',
    description: 'Sponsorship payment',
    amount: '900.00',
    type: 'income',
    status: 'approved',
    sheet: 'General',
    category: 'Sponsorship',
    party: 'Harbour Diving Supplies',
    reference: 'SPONSOR-Q1',
    activity: null,
    notes: 'Quarter-one sponsor installment.',
    version: 1,
    created_at: '2026-03-04T09:18:00.000Z',
    modified_at: '2026-03-04T09:18:00.000Z',
    modified_by: 'Demo Treasurer',
  },
  {
    id: 'tx-005',
    date: '2026-03-15',
    description: 'Trip fees received',
    amount: '450.00',
    type: 'income',
    status: 'approved',
    sheet: 'Expeditions',
    category: 'Events',
    party: 'Weekend participants',
    reference: 'COASTAL-FEES',
    activity: '2026-03-15 to 2026-03-16 Coastal Dive Weekend',
    notes: null,
    version: 1,
    created_at: '2026-03-15T08:20:00.000Z',
    modified_at: '2026-03-15T08:20:00.000Z',
    modified_by: 'Demo Treasurer',
  },
  {
    id: 'tx-006',
    date: '2026-03-15',
    description: 'Fuel and launch fees',
    amount: '162.00',
    type: 'expense',
    status: 'approved',
    sheet: 'Expeditions',
    category: 'Travel',
    party: 'East Coast Launch',
    reference: 'BOAT-315',
    activity: '2026-03-15 to 2026-03-16 Coastal Dive Weekend',
    notes: null,
    version: 1,
    created_at: '2026-03-15T17:40:00.000Z',
    modified_at: '2026-03-15T17:40:00.000Z',
    modified_by: 'Demo Treasurer',
  },
  {
    id: 'tx-007',
    date: '2026-03-16',
    description: 'Bunkhouse accommodation',
    amount: '220.00',
    type: 'expense',
    status: 'approved',
    sheet: 'Expeditions',
    category: 'Travel',
    party: 'Anstruther Bunkhouse',
    reference: 'BUNK-316',
    activity: '2026-03-15 to 2026-03-16 Coastal Dive Weekend',
    notes: null,
    version: 1,
    created_at: '2026-03-16T19:12:00.000Z',
    modified_at: '2026-03-16T19:12:00.000Z',
    modified_by: 'Demo Treasurer',
  },
  {
    id: 'tx-008',
    date: '2026-04-02',
    description: 'Grant installment',
    amount: '1200.00',
    type: 'income',
    status: 'approved',
    sheet: 'General',
    category: 'Grants',
    party: 'Athletic Union',
    reference: 'AU-GRANT-1',
    activity: null,
    notes: 'First installment toward kit replacement.',
    version: 1,
    created_at: '2026-04-02T11:05:00.000Z',
    modified_at: '2026-04-02T11:05:00.000Z',
    modified_by: 'Demo Treasurer',
  },
  {
    id: 'tx-009',
    date: '2026-04-10',
    description: 'Regulator servicing',
    amount: '410.00',
    type: 'expense',
    status: 'approved',
    sheet: 'General',
    category: 'Equipment',
    party: 'Aqua Workshop',
    reference: 'KIT-0410',
    activity: null,
    notes: 'Five regulator sets serviced and tested.',
    version: 1,
    created_at: '2026-04-10T13:00:00.000Z',
    modified_at: '2026-04-10T13:00:00.000Z',
    modified_by: 'Demo Treasurer',
  },
  {
    id: 'tx-010',
    date: '2026-04-18',
    description: 'Social ticket sales',
    amount: '180.00',
    type: 'income',
    status: 'approved',
    sheet: 'Social',
    category: 'Events',
    party: 'Club members',
    reference: 'SOCIAL-TIX',
    activity: '2026-04-18 Spring Social',
    notes: null,
    version: 1,
    created_at: '2026-04-18T16:10:00.000Z',
    modified_at: '2026-04-18T16:10:00.000Z',
    modified_by: 'Demo Treasurer',
  },
  {
    id: 'tx-011',
    date: '2026-04-18',
    description: 'Venue hire',
    amount: '95.00',
    type: 'expense',
    status: 'approved',
    sheet: 'Social',
    category: 'Social',
    party: 'Union Events Office',
    reference: 'SOCIAL-VENUE',
    activity: '2026-04-18 Spring Social',
    notes: null,
    version: 1,
    created_at: '2026-04-18T16:40:00.000Z',
    modified_at: '2026-04-18T16:40:00.000Z',
    modified_by: 'Demo Treasurer',
  },
  {
    id: 'tx-012',
    date: '2026-04-21',
    description: 'Merchandise order',
    amount: '240.00',
    type: 'expense',
    status: 'pending',
    sheet: 'General',
    category: 'Admin',
    party: 'Campus Print',
    reference: 'MERCH-0421',
    activity: null,
    notes: 'Hoodies and committee polos.',
    version: 1,
    created_at: '2026-04-21T09:50:00.000Z',
    modified_at: null,
    modified_by: null,
  },
  {
    id: 'tx-013',
    date: '2026-04-24',
    description: 'Travel reimbursement',
    amount: '84.00',
    type: 'income',
    status: 'pending',
    sheet: 'Training',
    category: 'Grants',
    party: 'University Sports Centre',
    reference: 'TRAVEL-CLAIM',
    activity: '2026-02-03 Pool Training Night',
    notes: 'Awaiting transfer from sports office.',
    version: 1,
    created_at: '2026-04-24T15:11:00.000Z',
    modified_at: null,
    modified_by: null,
  },
  {
    id: 'tx-014',
    date: '2026-04-25',
    description: 'Catering receipt',
    amount: '22.00',
    type: 'expense',
    status: 'rejected',
    sheet: 'Social',
    category: 'Social',
    party: 'Corner Store',
    reference: 'SOCIAL-RECEIPT',
    activity: '2026-04-18 Spring Social',
    notes: 'Duplicate claim.',
    version: 1,
    created_at: '2026-04-25T10:44:00.000Z',
    modified_at: '2026-04-26T08:32:00.000Z',
    modified_by: 'Demo Treasurer',
  },
  {
    id: 'tx-015',
    date: '2026-04-27',
    description: 'Cylinder testing',
    amount: '64.00',
    type: 'expense',
    status: 'approved',
    sheet: 'Training',
    category: 'Equipment',
    party: 'Fife Hydrostatic Testing',
    reference: 'CYL-0427',
    activity: null,
    notes: null,
    version: 1,
    created_at: '2026-04-27T12:28:00.000Z',
    modified_at: '2026-04-27T12:28:00.000Z',
    modified_by: 'Demo Treasurer',
  },
];

const plannedTemplates: PlannedTemplateRow[] = [
  {
    id: 'pt-storage',
    start_date: '2026-01-05',
    description: 'Kit storage rent',
    amount: '85.00',
    type: 'expense',
    frequency: 'monthly',
    target_sheet: 'General',
    category: 'Admin',
    party: 'Town Storage',
    activity: null,
    notes: 'Monthly lockup for club cylinders and spares.',
    end_date: null,
    occurrence_count: null,
    skipped_dates: '[]',
    fulfilled_dates: '["2026-01-05","2026-02-05","2026-03-05"]',
    version: 1,
    created_at: '2026-01-01T09:30:00.000Z',
  },
  {
    id: 'pt-membership',
    start_date: '2026-05-08',
    description: 'Guest session invoice',
    amount: '140.00',
    type: 'income',
    frequency: 'once',
    target_sheet: 'Training',
    category: 'Membership',
    party: 'Guest session participants',
    activity: '2026-05-08 Guest Taster Session',
    notes: 'Invoice for a one-off taster evening.',
    end_date: null,
    occurrence_count: null,
    skipped_dates: '[]',
    fulfilled_dates: '[]',
    version: 1,
    created_at: '2026-04-12T10:10:00.000Z',
  },
  {
    id: 'pt-loch',
    start_date: '2026-05-16',
    description: 'Minibus and fuel booking',
    amount: '260.00',
    type: 'expense',
    frequency: 'once',
    target_sheet: 'Expeditions',
    category: 'Travel',
    party: 'Student Transport',
    activity: '2026-05-16 to 2026-05-17 Loch Dive Weekend',
    notes: 'Weekend transport booking.',
    end_date: null,
    occurrence_count: null,
    skipped_dates: '[]',
    fulfilled_dates: '[]',
    version: 1,
    created_at: '2026-04-14T11:25:00.000Z',
  },
  {
    id: 'pt-affiliation',
    start_date: '2026-09-01',
    description: 'BSAC affiliation fee',
    amount: '180.00',
    type: 'expense',
    frequency: 'yearly',
    target_sheet: 'General',
    category: 'Admin',
    party: 'BSAC',
    activity: null,
    notes: 'Annual governing body fee.',
    end_date: null,
    occurrence_count: null,
    skipped_dates: '[]',
    fulfilled_dates: '[]',
    version: 1,
    created_at: '2026-04-20T09:40:00.000Z',
  },
];

const attachments: AttachmentRow[] = [
  {
    id: 'att-001',
    transaction_id: 'tx-008',
    filename: 'grant-award-letter.pdf',
    stored_name: 'grant-award-letter.pdf',
    mime_type: 'application/pdf',
    file_size: 245000,
    created_at: '2026-04-02T11:06:00.000Z',
  },
  {
    id: 'att-002',
    transaction_id: 'tx-008',
    filename: 'bank-confirmation.png',
    stored_name: 'bank-confirmation.png',
    mime_type: 'image/png',
    file_size: 180400,
    created_at: '2026-04-02T11:07:00.000Z',
  },
  {
    id: 'att-003',
    transaction_id: 'tx-009',
    filename: 'service-invoice.pdf',
    stored_name: 'service-invoice.pdf',
    mime_type: 'application/pdf',
    file_size: 198100,
    created_at: '2026-04-10T13:01:00.000Z',
  },
  {
    id: 'att-004',
    transaction_id: 'tx-010',
    filename: 'ticket-summary.csv',
    stored_name: 'ticket-summary.csv',
    mime_type: 'text/csv',
    file_size: 8400,
    created_at: '2026-04-18T16:11:00.000Z',
  },
];

const invoices: InvoiceRow[] = [
  {
    id: 'inv-001',
    invoice_number: 'FDR-20260501-01',
    date: '2026-05-01',
    due_date: '2026-05-15',
    from_name: 'SubAqua Club',
    from_address: 'Students Union, St Andrews',
    to_name: 'Guest Session Participants',
    to_address: null,
    line_items: JSON.stringify({
      items: [
        { description: 'Guest session places', quantity: 4, unitPrice: 25 },
        { description: 'Equipment hire', quantity: 4, unitPrice: 10 },
      ],
      taxRate: 0,
      accentMode: 'fidra',
    }),
    subtotal: '140.00',
    notes: 'Demo invoice linked to a one-off planned income item.',
    bank_details: 'Sort 00-00-00 / Account 12345678',
    planned_template_id: 'pt-membership',
    status: 'draft',
    transaction_id: null,
    paid_at: null,
    planned_template_snapshot: null,
    version: 1,
    created_at: '2026-04-20T12:20:00.000Z',
    modified_at: null,
    modified_by: null,
  },
];

export function createDemoDataState(): DemoDataState {
  return {
    transactions: structuredClone(transactions),
    sheets: structuredClone(sheets),
    plannedTemplates: structuredClone(plannedTemplates),
    attachments: structuredClone(attachments),
    invoices: structuredClone(invoices),
    incomeCategories: ['Membership', 'Grants', 'Sponsorship', 'Events', 'Fundraising'],
    expenseCategories: ['Training', 'Travel', 'Equipment', 'Social', 'Admin'],
    activityNotes: {
      '2026-02-03 Pool Training Night': 'Pool costs were later offset by a university reimbursement claim.',
      '2026-03-15 to 2026-03-16 Coastal Dive Weekend': 'Strong turnout, but transport costs ran hotter than expected.',
      '2026-04-18 Spring Social': 'Good ticket uptake; likely worth repeating in Michaelmas.',
      '2026-05-16 to 2026-05-17 Loch Dive Weekend': 'Planned loch weekend with shared transport and accommodation costs.',
    },
    currentSheet: 'All Sheets',
    uiPreferences: {
      tableZoom: 0.8,
      plannedTableZoom: 0.8,
      activitiesTableZoom: 0.8,
      showPlanned: true,
      filteredBalanceMode: false,
      theme: 'light',
      reportOrgName: 'SubAqua Club',
    },
    fyStartMonth: 8,
    profile: { name: 'Demo Treasurer', initials: 'DT' },
    currentUser: { displayName: 'Demo Treasurer', source: 'profile' },
    dbInfo: {
      path: '/demo/SubAqua Demo.fdra',
      name: 'SubAqua Demo.fdra',
    },
    invoiceDefaults: {
      fromName: 'SubAqua Club',
      fromAddress: 'Students Union, St Andrews',
      bankDetails: 'Sort 00-00-00 / Account 12345678',
      notes: 'Payment due within 14 days.',
      logoPath: '',
      logoData: '',
      counter: JSON.stringify({ date: '20260501', count: 1 }),
      accentMode: 'fidra',
    },
    cloudConfig: null,
    cloudStatus: {
      connected: false,
      connectionStatus: 'offline',
      isSyncing: false,
      pendingCount: 0,
      authSession: null,
      authMode: null,
    },
    localSyncConfig: null,
    localSyncStatus: {
      enabled: false,
      state: 'stopped',
      lastExportAt: null,
      lastImportAt: null,
      pendingConflicts: 0,
      lastError: null,
      syncFolder: null,
    },
  };
}
